version: '3'

services:
  app:
    build: .
    ports:
      - "8181:8080"
    volumes:
      - ./tmp:/app/tmp

  libreoffice:
    image: ubuntu:latest
    command: tail -f /dev/null
    volumes:
      - ./tmp:/app/tmp
